# Generated by Django 6.0.5 on 2026-05-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_commande_is_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='isCancelled',
            field=models.BooleanField(default=False),
        ),
    ]
